name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push(debian)
        uses: docker/build-push-action@v4
        with:
          context: docker-mirakurun-epgstation
          file: debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/epgstation:debian-latest

      - name: Build and push(alpine)
        uses: docker/build-push-action@v4
        with:
          context: docker-mirakurun-epgstation
          file: alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/epgstation:alpine-latest
